kind: Service
apiVersion: v1
metadata:
  name: apa-spark-master
  # namespace: spark
spec:
  type: NodePort
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    component: apa-spark-master
