kind: Deployment
apiVersion: apps/v1
metadata:
  name: apa-spark-worker
  # namespace: spark
spec:
  serviceAccountName: default
  replicas: 2 
  selector:
    matchLabels:
      component: apa-spark-worker
  template:
    metadata:
      labels:
        component: apa-spark-worker
    spec:
      containers:
        - name: apa-spark-worker
          image: <custom-image>
          imagePullPolicy: Always
          command: ["/spark-worker"]
          env:
          - name: SPARK_WORKER_CORES
            value: "10"
          - name: SPARK_WORKER_MEMORY
            value: 20g 
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
