kind: Deployment
apiVersion: apps/v1
metadata:
  name: apa-spark-master
  # namespace: spark
spec:
  replicas: 1 
  selector:
    matchLabels:
      component: apa-spark-master
  template:
    metadata:
      labels:
        component: apa-spark-master
    spec:
      containers:
        - name: apa-spark-master
          image: <custom-image>
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
