#!/bin/bash

. /common.sh

if ! getent hosts apa-spark-master; then
  sleep 5
  exit 0
fi

#/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://apa-spark-master:7077 --webui-port 8081
/opt/spark/sbin/start-worker.sh


memory = '10g'
pyspark_submit_args = ' --driver-memory ' + memory + ' pyspark-shell'
os.environ["PYSPARK_SUBMIT_ARGS"] = pyspark_submit_args
